CREATE DATABASE AirCompanyDB
USE AirCompanyDB
GO

CREATE TABLE Client
(
	Id INT PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(50) NULL,
	Phone NVARCHAR(15) NULL,
	Nationality NVARCHAR(30) NOT NULL
)

CREATE TABLE PlaneModel
(
	Id INT PRIMARY KEY,
	Model NVARCHAR(30) NOT NULL,
	SeatsNumber SMALLINT NOT NULL,
	
)

CREATE TABLE "Route"
(
	Id INT PRIMARY KEY,
	DepartureAirPort  NVARCHAR(50) NOT NULL,
	ArrivalAirPort  NVARCHAR(50) NOT NULL,
)

GO

CREATE TABLE Passport
(
	Id INT PRIMARY KEY REFERENCES Client (Id),
	ExpirationDate DATE NOT NULL,
	Number NVARCHAR(20) NOT NULL,
	RecordNumber NVARCHAR(30) NOT NULL,
	Gender NVARCHAR(5) NOT NULL

)

CREATE TABLE Plane
(
	Id INT PRIMARY KEY,
	PlaneModelId INT FOREIGN KEY REFERENCES PlaneModel (Id) NOT NULL,
	ExpirationDate DATE NOT NULL,
	ManufactureDate DATE NOT NULL
)

GO

CREATE TABLE Flight
(
	Id INT PRIMARY KEY,
	RouteIdId INT FOREIGN KEY REFERENCES "Route" (Id) NOT NULL,
	PlaneId INT FOREIGN KEY REFERENCES Plane (Id) NOT NULL,
	DepartureTime DATETIME NOT NULL,
	ArrivalTime DATETIME NULL
)

CREATE TABLE PlaneToRoute
(
	Id INT PRIMARY KEY,
	RouteIdId INT FOREIGN KEY REFERENCES "Route" (Id) NOT NULL,
	PlaneId INT FOREIGN KEY REFERENCES Plane (Id) NOT NULL
)

GO

CREATE TABLE Ticket
(
	Id INT PRIMARY KEY,
	ClientId INT FOREIGN KEY REFERENCES Client (Id) NULL,
	PassportId INT FOREIGN KEY REFERENCES Passport (Id) NULL,
	FlightId INT FOREIGN KEY REFERENCES Flight (Id) NOT NULL,
	TicketNumber INT NOT NULL,
	Class NVARCHAR(20) NOT NULL,
	SeatNumber NVARCHAR(5) NOT NULL
)
